### ISSUE TITLE
Turns off after automation turns it on

### ISSUE THREAD

**Issue by andysammy1221-alt** [jeatheak/Mitsubishi-WF-RAC-Integration#180]
![Screenshot_20251220_110151_GitHub.jpg](https://github.com/user-attachments/assets/854a0f7d-c26b-4ef1-8f60-2e003caf035e)

This is a fantastic easy to set up HACS! Unfortunately after everything set up, I put simple automation to turn on and 5 seconds after it turn on and implement all settings, it turns off, can you please help with that?

**Comment by blues-sechseck** [comment]
Thanks for the report! There's not quite enough here to tell whether this is an integration issue or something in the automation itself — could you share:

1. The automation's YAML (or a screenshot of all its steps/actions, not just the trigger)
2. The Home Assistant log around the time it turns back off (Settings → System → Logs, filtered for `mitsubishi_wf_rac`)
3. Whether anything else could be sending a command around the same time (the physical remote, the Smart M-Air app, another automation)

Leaving this open pending more info.

**Comment by blues-sechseck** [comment]
Circling back — I recently fixed a bug that could match this: if `target_offset_cool`/`target_offset_heat` was set to a non-zero value in the integration's options, the climate entity kept reporting a stale target temperature after every command. That can trip an automation which checks the temperature attribute into re-sending commands right after turn-on. Fixed in 2026.9.1 (released today).

A couple of things that would help confirm:
1. Do you have `target_offset_cool`/`target_offset_heat` set to anything other than 0?
2. Could you share your automation's YAML and a debug log from around when it turns off? (Settings → System → Logs, filtered for `mitsubishi_wf_rac`)

If you get a chance to update to 2026.9.1 and see if it still happens, that'd help either way.

**Comment by blues-sechseck** [comment]
Still hoping to see your automation YAML or a debug log from around when it turns back off — that's what would actually move this forward.

Separately, unrelated to this issue: 2026.9.2-beta2 just went out with some new sensors (compressor frequency/current, EEV valve position) if you're interested, but it doesn't touch what you're seeing here.

**Comment by andysammy1221-alt** [comment]
Hi, sorry i haven't replied quickly and thank you for following it up!

I have 2 automations (probably unnecessary but works for me) which I set up
ages ago when people first presented itself at the start, here are the yaml
codes:

"alias: HEAT - ON - Downstairs air con
description: ''
triggers:
  - alias: <15
    type: temperature
    device_id: c4b57ab37a11f6fa0134573e99596a92
    entity_id: f4c9ec0d6d59ec6705c1380c9abc830d
    domain: sensor
    trigger: device
    below: 15
    enabled: false
  - alias: <16
    type: temperature
    device_id: c4b57ab37a11f6fa0134573e99596a92
    entity_id: f4c9ec0d6d59ec6705c1380c9abc830d
    domain: sensor
    trigger: device
    below: 16
    enabled: false
  - alias: <17
    type: temperature
    device_id: c4b57ab37a11f6fa0134573e99596a92
    entity_id: f4c9ec0d6d59ec6705c1380c9abc830d
    domain: sensor
    trigger: device
    below: 17
    enabled: false
  - alias: <19
    type: temperature
    device_id: c4b57ab37a11f6fa0134573e99596a92
    entity_id: f4c9ec0d6d59ec6705c1380c9abc830d
    domain: sensor
    trigger: device
    below: 19
    enabled: false
  - type: temperature
    device_id: c4b57ab37a11f6fa0134573e99596a92
    entity_id: f4c9ec0d6d59ec6705c1380c9abc830d
    domain: sensor
    trigger: device
    below: 21
    alias: <21
    enabled: false
  - alias: <20.5
    type: temperature
    device_id: c4b57ab37a11f6fa0134573e99596a92
    entity_id: f4c9ec0d6d59ec6705c1380c9abc830d
    domain: sensor
    trigger: device
    below: 20.5
    enabled: false
  - alias: Kitchen heater - below 23
    trigger: numeric_state
    entity_id:
      - climate.heater
    attribute: current_temperature
    below: 23
    enabled: false
  - type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 16.5
    alias: '16.5'
    enabled: false
  - type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 18
    alias: '18'
    enabled: false
  - type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 17.5
    alias: '17.5'
    enabled: false
  - alias: '19'
    type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 19
    enabled: false
  - alias: '20'
    type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 20
    enabled: false
  - alias: '20.5'
    type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 20.5
    enabled: false
  - alias: '21.5'
    type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 21.5
    enabled: false
  - alias: '22.3'
    type: temperature
    device_id: 545933553e015f538f5c363fcedc41e5
    entity_id: 91495b1ccbc5386dea6187a07abc4e8a
    domain: sensor
    trigger: device
    below: 22.3
    enabled: false
  - trigger: temperature.changed
    target:
      entity_id:
        - sensor.air_quality_sensor_temperature
        - sensor.big_air_con_indoor
    options:
      threshold:
        type: any
conditions:
  - condition: or
    conditions:
      - condition: time
        after: '06:00:00'
        before: '12:59:00'
      - condition: time
        after: '16:00:00'
        before: '19:30:00'
  - condition: numeric_state
    entity_id: sensor.wantirna_temp_feels_like
    below: 13
    enabled: true
  - condition: state
    entity_id: climate.big_air_con
    state:
      - 'off'
  - condition: state
    entity_id: input_boolean.living_room_ac_state
    state:
      - 'off'
  - condition: temperature.is_value
    target:
      entity_id: sensor.heater_temperature
    options:
      threshold:
        type: below
        value:
          active_choice: number
          number: 19
          unit_of_measurement: °C
  - condition: temperature.is_value
    target:
      entity_id: sensor.air_quality_sensor_temperature
    options:
      threshold:
        type: below
        value:
          active_choice: number
          number: 20
          unit_of_measurement: °C
  - condition: device
    device_id: e6a52e38a5a20aba22aa770993b70b31
    domain: alarm_control_panel
    entity_id: af4c2fc9b050eb33a413bb559934ff05
    type: is_disarmed
actions:
  - action: input_boolean.turn_on
    target:
      entity_id:
        - input_boolean.living_room_ac_state
    data: {}
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: select
    entity_id: 8e979cb68b068998f38162d384dd5e08
    type: select_option
    option: Left-Center
    continue_on_error: true
  - action: climate.set_temperature
    metadata: {}
    target:
      entity_id: climate.big_air_con
    data:
      temperature: 22
    enabled: true
    continue_on_error: true
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: select
    entity_id: 2fceab4baef9e7cbc84ffe32b5148397
    type: select_option
    option: auto
    continue_on_error: true
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: climate
    entity_id: b204abbebd62f16b324733ea62f6621f
    type: set_hvac_mode
    hvac_mode: heat
    continue_on_error: true
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: select
    entity_id: 3a8e512967a2269926efb24c9513d496
    type: select_option
    option: highest
    continue_on_error: true
  - alias: Samsung notification
    action: notify.mobile_app_samsung_phone
    metadata: {}
    data:
      message: HEAT - ON - Downstairs air con
    enabled: true
    continue_on_error: true
  - action: notify.mobile_app_honor
    metadata: {}
    data:
      message: HEAT - ON - Downstairs air con
    continue_on_error: true
    alias: Honor notification
mode: single



alias: 'HEAT: ON - 2 - Downstairs air con - day'
description: ''
triggers:
  - trigger: state
    entity_id:
      - climate.big_air_con
    attribute: hvac_action
    from:
      - 'off'
    to:
      - heating
    for:
      hours: 0
      minutes: 0
      seconds: 1
conditions:
  - condition: state
    entity_id: automation.downstairs_air_con_on_heat_day
    state:
      - 'on'
actions:
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.living_room_ac_state
    data: {}
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: select
    entity_id: 2fceab4baef9e7cbc84ffe32b5148397
    type: select_option
    option: auto
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: select
    entity_id: 8e979cb68b068998f38162d384dd5e08
    type: select_option
    option: Left-Center
  - action: climate.set_temperature
    metadata: {}
    target:
      entity_id: climate.big_air_con
    data:
      temperature: 23
    enabled: true
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: climate
    entity_id: b204abbebd62f16b324733ea62f6621f
    type: set_hvac_mode
    hvac_mode: heat
  - device_id: 545933553e015f538f5c363fcedc41e5
    domain: select
    entity_id: 3a8e512967a2269926efb24c9513d496
    type: select_option
    option: Highest
  - action: notify.mobile_app_samsung_phone
    metadata: {}
    data:
      message: 'HEAT: ON - 2 - Downstairs air con - day'
mode: single

**Comment by blues-sechseck** [comment]
Thanks for the automation YAML, that helps.

Before digging into the automations themselves — have you had a chance to update to 2026.9.1 yet? That's the main thing to check first: the stale-target-temperature bug I mentioned could easily explain a turn-off right after turn-on, and if it's already fixed on your end this gets a lot simpler.

One thing I did notice in your second automation ("HEAT: ON - 2 - Downstairs air con - day"): it fires again right after `hvac_action` changes to heating and re-sends the vane/temperature/hvac_mode/fan-speed commands — with a different target temperature (23°C) than the first automation used (22°C). Worth a look either way, but let's start with the version question.

If it's still happening on 2026.9.1, a debug log from around the turn-off (Settings → System → Logs, filtered for `mitsubishi_wf_rac`) would be the next step.

**Comment by andysammy1221-alt** [comment]
Thanks Daniel, I'll update that.

My Core is on .8, no further updates, how can I change to .9? Some
attachments of current position.

Today I will try if issue still happening and then I'll update you.

Thanks again!

**Comment by andysammy1221-alt** [comment]
Hi,

I disabled Heat 2 and only turned on the first one and it worked, one of
your previous updates must've worked, thank you!

Regards,

Andy
